-- ============================================
-- PROMPT SEEDS MASTER RUNNER
-- ============================================
-- This script runs all prompt seed files in the correct order.
-- Run this after the prompt system migration has been applied.
--
-- Order:
-- 1. Grade-level prompts (00_grade_prompts.sql)
-- 2. Subject global prompts (01_subject_prompts.sql)
-- 3. User profile prompts (02_user_profile_prompts.sql)
-- 4. Unit prompts (units/*.sql)
-- 5. Topic prompts (topics/**/*.sql)
--
-- Note: Use seed-prompts.js for automated seeding via Node.js
-- ============================================

-- Step 1: Verify prompt_templates table exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'prompt_templates') THEN
    RAISE EXCEPTION 'Table prompt_templates does not exist. Run the prompt system migration first.';
  END IF;
END $$;

-- Step 2: Show current counts before seeding
SELECT 'Before seeding' as status,
       prompt_type,
       COUNT(*) as count
FROM prompt_templates
GROUP BY prompt_type
ORDER BY prompt_type;

-- Step 3: Run seed files
-- Note: Use \i with psql or run these files individually

-- Grade prompts
\i 00_grade_prompts.sql

-- Subject prompts
\i 01_subject_prompts.sql

-- User profile prompts
\i 02_user_profile_prompts.sql

-- Unit prompts (run each subject)
\i units/math_units.sql
\i units/science_units.sql
\i units/reading_units.sql
\i units/history_units.sql

-- Topic prompts would be run per-file from topics directory
-- These are generated by scripts/generate-prompt-seeds.js

-- Step 4: Verify results
SELECT 'After seeding' as status,
       prompt_type,
       COUNT(*) as count
FROM prompt_templates
GROUP BY prompt_type
ORDER BY prompt_type;

-- Step 5: Summary
SELECT
  'Total prompts seeded' as status,
  COUNT(*) as total_count,
  COUNT(DISTINCT prompt_type) as type_count,
  COUNT(DISTINCT subject_id) FILTER (WHERE subject_id IS NOT NULL) as subjects_with_prompts,
  COUNT(DISTINCT unit_id) FILTER (WHERE unit_id IS NOT NULL) as units_with_prompts,
  COUNT(DISTINCT topic_id) FILTER (WHERE topic_id IS NOT NULL) as topics_with_prompts,
  COUNT(DISTINCT grade_level) FILTER (WHERE grade_level IS NOT NULL) as grade_levels_with_prompts
FROM prompt_templates;

SELECT 'Prompt seeds completed successfully!' as status;
